package controller;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.*;

import javafx.fxml.Initializable;

import java.io.IOException;
import java.net.URL;
import java.util.Optional;
import java.util.ResourceBundle;

import javafx.scene.control.cell.PropertyValueFactory;
import main.GenerateIdNumber;
import main.Staging;
import model.Inventory;
import model.Part;
import model.Product;

/**
 * This class is a form used to add products to inventory.
 */
public class AddProductForm implements Initializable {
    private Staging staging = new Staging();
    private static ObservableList<Part> filteredParts = FXCollections.observableArrayList();


    @FXML
    private TextField IDTxt;

    @FXML
    private TableView<Part> addPartTableView;

    @FXML
    private TableColumn<Part, Integer> addPartIDCol;

    @FXML
    private TableColumn<Part, Integer> addPartInventoryLevelCol;

    @FXML
    private TableColumn<Part, String> addPartNameCol;

    @FXML
    private TableColumn<Part, Double> addPartPricePerUnitCol;

    @FXML
    private TextField inventoryTxt;

    @FXML
    private TextField maxTxt;

    @FXML
    private TextField minTxt;

    @FXML
    private TextField nameTxt;

    @FXML
    private TextField priceTxt;

    @FXML
    private TableView<Part> removeAssociatedPartTableView;

    @FXML
    private TableColumn<Part, Integer> removePartIDCol;

    @FXML
    private TableColumn<Part, Integer> removePartInventoryLevelCol;

    @FXML
    private TableColumn<Part, String> removePartNameCol;

    @FXML
    private TableColumn<Part, Double> removePartPricePerUnitCol;

    @FXML
    private TextField searchPartTxt;

    /** On action, adds part to ObservableList.
     * @param event autogenerated
     */
    @FXML
    void onActionAddPart(ActionEvent event) {
        Part part = (Part)addPartTableView.getSelectionModel().getSelectedItem();
        filteredParts.add(part);
    }

    /** On action, cancel form.
     * @param event needed in order to change scene
     * @throws IOException needed in order to change scene
     */
    @FXML
    void onActionCancel(ActionEvent event) throws IOException { // sends you back to main menu
        // creating a confirmation confirm dialog box on cancel
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION,"This will clear all text field values, do you want to continue?");
        Optional<ButtonType> result = alert.showAndWait();
        if(result.isPresent() && result.get() == ButtonType.OK) {
            staging.stagingMethod(event, "/view/MainForm.fxml");
        }
    }

    /** On action, remove part from ObservableList.
     * @param event unused
     */
    @FXML
    void onActionRemoveAssociatedPart(ActionEvent event) {
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION,"Are you sure you want to delete?");
        Optional<ButtonType> result = alert.showAndWait();
        if(result.isPresent() && result.get() == ButtonType.OK) {
            Part part = (Part) removeAssociatedPartTableView.getSelectionModel().getSelectedItem();
            filteredParts.remove(part);
        }
    }

    /** On action, add new product to inventory.
     * @param event needed in order to change scene
     * @throws IOException needed in order to change scene
     */
    @FXML
    void onActionSave(ActionEvent event) throws IOException {
        try {
            if (Integer.parseInt(this.minTxt.getText()) > Integer.parseInt(this.maxTxt.getText())) {
                Alert alertError = new Alert(Alert.AlertType.ERROR);
                alertError.setTitle("Error Dialog");
                alertError.setContentText("Your min must be lower than your max.");
                alertError.showAndWait();
                return;
            }
            if (Integer.parseInt(this.inventoryTxt.getText()) < Integer.parseInt(this.minTxt.getText()) || Integer.parseInt(this.minTxt.getText()) > Integer.parseInt(this.maxTxt.getText())) {
                Alert alertError = new Alert(Alert.AlertType.ERROR);
                alertError.setTitle("Error Dialog");
                alertError.setContentText("Your inventory must be between your min and max.");
                alertError.showAndWait();
                return;
            }

            Product product = new Product(GenerateIdNumber.getNewProductNumber(),
                    nameTxt.getText(),
                    Double.parseDouble(priceTxt.getText()),
                    Integer.parseInt(inventoryTxt.getText()),
                    Integer.parseInt(minTxt.getText()),
                    Integer.parseInt(maxTxt.getText())
            );

            for (Part part : filteredParts) { // add all parts from ObservableList to the Product object
                product.addAssociatedPart(part);
            }

            Inventory.addProduct(product);      // adds product to inventory

            staging.stagingMethod(event, "/view/MainForm.fxml");
        }catch(NumberFormatException e){
                Alert alertError = new Alert(Alert.AlertType.ERROR);
                alertError.setTitle("Error Dialog");
            alertError.setContentText("Please enter valid values in text fields!\n" + e);
                alertError.showAndWait();
        }
    }

    /** Search part through id, if not exist, then name. There is a NumberFormat exception used here. It is used to
     * search for part based on id first. If there is a NumberFormatException (ex: a string entered), it will then
     * look for part based on part name. In the future you could have 2 different searches, or you could expand search by searching by price.
     * @param event unused
     */
    @FXML
    void onActionSearchPart(ActionEvent event) { // searching part by either id or name/partial name (searches id first)
        try{ // try looking up parts through id first
            addPartTableView.setItems(FXCollections.observableArrayList(Inventory.lookupPart(Integer.parseInt(searchPartTxt.getText()))));
        }catch (NumberFormatException e){ // if there is a number NumberFormatException, then we will search through part name
            addPartTableView.setItems(Inventory.lookupPart(searchPartTxt.getText()));
        }
    }

    /** Runs first when class is called.
     * @param url unused
     * @param resourceBundle unused
     */
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) { // runs on open
        System.out.println("add product form opened");

        // Populating tables
        addPartTableView.setItems(Inventory.getAllParts());

        // These have to match exactly with the part class's "getters" ex: getId = id or getName = name
        addPartIDCol.setCellValueFactory(new PropertyValueFactory<>("id"));
        addPartNameCol.setCellValueFactory(new PropertyValueFactory<>("name"));
        addPartInventoryLevelCol.setCellValueFactory(new PropertyValueFactory<>("stock"));
        addPartPricePerUnitCol.setCellValueFactory(new PropertyValueFactory<>("price"));

        removeAssociatedPartTableView.setItems(filteredParts);

        // These have to match exactly with the part class's "getters" ex: getId = id or getName = name
        removePartIDCol.setCellValueFactory(new PropertyValueFactory<>("id"));
        removePartNameCol.setCellValueFactory(new PropertyValueFactory<>("name"));
        removePartInventoryLevelCol.setCellValueFactory(new PropertyValueFactory<>("stock"));
        removePartPricePerUnitCol.setCellValueFactory(new PropertyValueFactory<>("price"));
    }
}
